[project]
name = "adiiva"
version = "0.1.0"
description = "Adiiva Take Home Assignment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[silero,deepgram,openai,cartesia,runner,websocket,tracing]",
    "opentelemetry-exporter-otlp-proto-http",
    "fastapi",
    "uvicorn[standard]",
    "python-jose[cryptography]",
    "redis[hiredis]",
    "python-multipart",
    "bcrypt>=4.0.0",
    "python-dotenv",
    "loguru"
]

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]
